[package]
name = "carla"
version = "0.1.0"
authors = ["reedts <j.reedts@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.0"
chrono-tz = "0.4.0"
tui = "0.12"
termion = "1.5"
ical = "0.6.*"
